"""initial migration

Revision ID: 2bc8d7f2aa9
Revises: None
Create Date: 2015-11-24 19:24:45.275983

"""

# revision identifiers, used by Alembic.
revision = '2bc8d7f2aa9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
